version: '{build}'
skip_tags: true
image: Visual Studio 2022
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/SerilogTimings.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 6m2isg5p2eMqbdrcnt0CXpgN0G3QMoUiRZsrSHJx94gSUECf8xl+zvwkFLmZYRSI
  skip_symbols: true
  on:
    branch: /^(dev|main)$/
